# circle.yml #
# machine:
#   go:
#     version: 1.9.1

version: 2

jobs:
  build:
    docker:
      - image: golang:1.9.1
    working_directory: /go/src/github.com/go-ego/gpy
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...   

# test:
#   post:
#     - go test -v -covermode=count -coverprofile=coverage.out
#     - bash <(curl -s https://codecov.io/bash) 
   